image: gradle:8-jdk21-alpine


before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME
  - mkdir -p $GRADLE_USER_HOME
  - touch $GRADLE_USER_HOME/gradle.properties
  - mkdir -p ~/plugins
  - echo "timesnakePluginDir=~/plugins" >> $GRADLE_USER_HOME/gradle.properties
  - echo "timesnakeUsername=gitlab-ci-token" >> $GRADLE_USER_HOME/gradle.properties
  - echo "timesnakePassword=$CI_JOB_TOKEN" >> $GRADLE_USER_HOME/gradle.properties

build:
  stage: build
  script: gradle assemble
  cache:
    paths:
      - .gradle/wrapper
    key:
      files:
        - gradle/wrapper/gradle-wrapper.properties
  tags:
    - gradle
  only:
    - tags