image: gradle:alpine

variables:
  GIT_STRATEGY: fetch

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME
  - mkdir -p $GRADLE_USER_HOME
  - touch $GRADLE_USER_HOME/gradle.properties
  - mkdir -p ~/plugins
  - echo "timesnakePluginDir=~/plugins" >> $GRADLE_USER_HOME/gradle.properties
  - echo "timesnakeUser=gitlab-ci-token" >> $GRADLE_USER_HOME/gradle.properties
  - echo "timesnakePassword=$CI_JOB_TOKEN" >> $GRADLE_USER_HOME/gradle.properties

build:
  stage: build
  script: gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle
  tags:
    - gradle