image: gradle:alpine

variables:
  GIT_STRATEGY: fetch

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

build:
  stage: build
  script: gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle
  tags:
    - gradle

include:
  - template: Code-Quality.gitlab-ci.yml

code_quality:
  services:
  tags:
    - cq-sans-dind